<<<<<<< HEAD
# Generated by Django 4.1.2 on 2023-02-15 06:40
=======
# Generated by Django 4.1.7 on 2023-02-28 21:17
>>>>>>> e6e48eaa3257401cc6e1fe5acee4a142cbea2185

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('cat_key', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=150)),
                ('clase', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('cert_key', models.AutoField(primary_key=True, serialize=False)),
                ('certificado', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_emp', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('empresa', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_e', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id_perm', models.AutoField(primary_key=True, serialize=False)),
<<<<<<< HEAD
                ('date_request', models.DateField(default=datetime.datetime(2023, 2, 15, 6, 40, 44, 518481, tzinfo=datetime.timezone.utc))),
                ('date_begin_work', models.DateField(default=datetime.datetime(2023, 2, 15, 6, 40, 44, 518481, tzinfo=datetime.timezone.utc))),
                ('date_end_work', models.DateField(default=datetime.datetime(2023, 2, 15, 6, 40, 44, 518481, tzinfo=datetime.timezone.utc))),
                ('type_permission', models.CharField(blank=True, default='', max_length=30)),
                ('pptr', models.CharField(default='', max_length=50)),
                ('work', models.CharField(blank=True, default='', max_length=200)),
                ('work_site', models.CharField(blank=True, default='', max_length=200)),
                ('work_desc', models.CharField(blank=True, default='', max_length=200)),
=======
                ('date_request', models.DateField(default=datetime.datetime(2023, 2, 28, 21, 17, 40, 966932, tzinfo=datetime.timezone.utc))),
                ('date_begin_work', models.DateField(default=datetime.datetime(2023, 2, 28, 21, 17, 40, 966932, tzinfo=datetime.timezone.utc))),
                ('date_end_work', models.DateField(default=datetime.datetime(2023, 2, 28, 21, 17, 40, 966932, tzinfo=datetime.timezone.utc))),
                ('type_permission', models.CharField(blank=True, default='', max_length=30)),
                ('pptr', models.CharField(default='', max_length=50, unique=True)),
                ('work', models.CharField(blank=True, default='', max_length=200)),
                ('work_site', models.CharField(blank=True, default='', max_length=200)),
                ('work_desc', models.TextField(blank=True)),
                ('instalacion', models.TextField(blank=True)),
>>>>>>> e6e48eaa3257401cc6e1fe5acee4a142cbea2185
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_reg', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id_coor', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('trabajador', models.CharField(max_length=300)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.region')),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id_sede', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('sede', models.CharField(max_length=150)),
                ('region', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.region')),
            ],
        ),
        migrations.CreateModel(
            name='Permisos_certificado',
            fields=[
                ('perm_cert', models.AutoField(primary_key=True, serialize=False)),
                ('certificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.certificado')),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.permiso')),
            ],
        ),
        migrations.CreateModel(
            name='Permiso_terminado',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=500)),
                ('folio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.permiso')),
            ],
        ),
        migrations.CreateModel(
            name='Permiso_Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.permiso')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.region')),
            ],
        ),
        migrations.AddField(
            model_name='permiso',
            name='coordinador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinador', to='app.trabajador'),
        ),
        migrations.AddField(
            model_name='permiso',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresa'),
        ),
        migrations.AddField(
            model_name='permiso',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.estado'),
        ),
        migrations.AddField(
            model_name='permiso',
            name='resp_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resp_area', to='app.trabajador'),
        ),
        migrations.AddField(
            model_name='permiso',
            name='resp_sitio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resp_sitio', to='app.trabajador'),
        ),
        migrations.AddField(
            model_name='permiso',
            name='work_cat',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.categoria'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.region'),
        ),
    ]
