# Generated by Django 4.1.7 on 2023-02-28 23:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permiso',
            name='date_begin_work',
            field=models.DateField(default=datetime.datetime(2023, 2, 28, 23, 5, 14, 339552, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='date_end_work',
            field=models.DateField(default=datetime.datetime(2023, 2, 28, 23, 5, 14, 339552, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='date_request',
            field=models.DateField(default=datetime.datetime(2023, 2, 28, 23, 5, 14, 339552, tzinfo=datetime.timezone.utc)),
        ),
    ]
