# Generated by Django 4.1.7 on 2023-02-28 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permiso',
            name='instalacion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='date_begin_work',
            field=models.DateField(default=datetime.datetime(2023, 2, 28, 16, 56, 45, 28363, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='date_end_work',
            field=models.DateField(default=datetime.datetime(2023, 2, 28, 16, 56, 45, 28363, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='date_request',
            field=models.DateField(default=datetime.datetime(2023, 2, 28, 16, 56, 45, 28363, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='pptr',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='work_desc',
            field=models.TextField(blank=True),
        ),
    ]
