# Generated by Django 4.1.7 on 2023-02-28 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_permiso_instalacion_alter_permiso_date_begin_work_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permiso',
            name='date_begin_work',
            field=models.DateField(default=datetime.datetime(2023, 2, 28, 17, 0, 28, 297457, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='date_end_work',
            field=models.DateField(default=datetime.datetime(2023, 2, 28, 17, 0, 28, 297457, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='date_request',
            field=models.DateField(default=datetime.datetime(2023, 2, 28, 17, 0, 28, 297457, tzinfo=datetime.timezone.utc)),
        ),
    ]
