# Generated by Django 4.1 on 2024-04-02 01:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_permiso_date_begin_work_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permiso',
            name='date_begin_work',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='date_end_work',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='date_request',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='permiso_region',
            name='permiso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_region', to='app.permiso'),
        ),
        migrations.AlterField(
            model_name='permisos_certificado',
            name='certificado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cert', to='app.certificado'),
        ),
        migrations.AlterField(
            model_name='permisos_certificado',
            name='permiso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_w_cert', to='app.permiso'),
        ),
        migrations.DeleteModel(
            name='Permiso_terminado',
        ),
    ]
